backend:
  name: github
  repo: baurine/try-gatsby

# the uploaded assets will put in `/admin/static/assets/` folder
# when build, the assets will output to `/public/assets/` folder
media_folder: static/assets
public_folder: assets

collections:
  - name: blog
    label: Blog
    folder: blog # the commited markdown file will put in `/blog/` folder
    create: true
    fields:
      - { name: path,  label: Path }
      - { name: date,  label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body,  label: Body, widget: markdown }
